name: wikipelis
description: "A new Flutter project."
publish_to: "none"
version: 1.0.5+6

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^17.0.1
  google_fonts: ^7.0.0
  google_nav_bar: ^5.0.6
  intl: ^0.20.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  isar_community_generator: ^3.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/gif/
    - assets/icon/
